server:
  port: 10086 # 服务端口
spring:
  application:
    name: eureka-server # eureka的服务名称
eureka:
  client:
    service-url: # eureka自己也是微服务，要把自己页注册到eureka之中
      defaultZone: http://127.0.0.1:10086/eureka